name: build

permissions:
  contents: write

on:
  push:
  schedule:
    - cron: "25 23 * * *"
  workflow_dispatch:
    inputs:
      sha:
        description: "The sha of the commit to build"
        required: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{steps.get_sha.outputs.sha}}
    steps:
      - id: get_sha
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{github.event.inputs.sha}}" ]
          then
            latestSha="${{github.event.inputs.sha}}"
          else
            latestSha="$(curl -L https://api.github.com/repos/SagerNet/sing-box/commits/dev-next | jq -r '.sha')"
          fi
          nowSha=$(curl -L https://github.com/AsenHu/box_builder/releases/download/quic/version.txt) || nowSha="false"
          if [ "$latestSha" != "$nowSha" ]
          then
            echo "sha=$latestSha"  >> $GITHUB_OUTPUT
            echo ${latestSha:0:7} > version.txt
            gh release delete --yes \
              --repo="${{github.repository}}" \
              --cleanup-tag quic
            gh release create "quic" \
              --repo="${{github.repository}}" \
              --title="${latestSha:0:7}" \
              --generate-notes
            gh release upload "quic" "version.txt" \
              --clobber \
              --repo="${{github.repository}}"
          else
            echo "sha=false" >> $GITHUB_OUTPUT
            exit
          fi

  linux_build:
    if: needs.prepare.outputs.sha != 'false'
    strategy:
      matrix:
        goamd: [v1, v2, v3, v4]
    env:
      GOOS: linux
      GOARCH: amd64
      GOAMD64: ${{matrix.goamd}}
      CGO_ENABLED: 0
      TAGS: with_quic
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'SagerNet/sing-box'
          ref: ${{needs.prepare.outputs.sha}}
      - uses: actions/setup-go@v5
      - name: build
        run : |
          make
          mv sing-box sing-box-${{env.GOOS}}-${{env.GOARCH}}-${{env.GOAMD64}}
      - uses: actions/upload-artifact@v4
        with:
          name: "sing-box-${{env.GOOS}}-${{env.GOARCH}}-${{env.GOAMD64}}"
          path: "sing-box-${{env.GOOS}}-${{env.GOARCH}}-${{env.GOAMD64}}"
      - name: upload
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "quic" "sing-box-${{env.GOOS}}-${{env.GOARCH}}-${{env.GOAMD64}}" \
            --clobber \
            --repo="${{github.repository}}"

  windows_build:
    if: needs.prepare.outputs.sha != 'false'
    strategy:
      matrix:
        goamd: [v1, v2, v3, v4]
    env:
      GOOS: windows
      GOARCH: amd64
      GOAMD64: ${{matrix.goamd}}
      CGO_ENABLED: 0
      TAGS: with_quic
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'SagerNet/sing-box'
          ref: ${{needs.prepare.outputs.sha}}
      - uses: actions/setup-go@v5
      - name: build
        run : |
          make
          mv sing-box.exe sing-box-${{env.GOOS}}-${{env.GOARCH}}-${{env.GOAMD64}}.exe
      - uses: actions/upload-artifact@v4
        with:
          name: "sing-box-${{env.GOOS}}-${{env.GOARCH}}-${{env.GOAMD64}}.exe"
          path: "sing-box-${{env.GOOS}}-${{env.GOARCH}}-${{env.GOAMD64}}.exe"
      - name: upload
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "quic" "sing-box-${{env.GOOS}}-${{env.GOARCH}}-${{env.GOAMD64}}.exe" \
            --clobber \
            --repo="${{github.repository}}"